DROP TABLE IF EXISTS delivery CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS payment CASCADE;
DROP TABLE IF EXISTS wb_order CASCADE;

DELETE FROM delivery WHERE id IS NOT NULL;
DELETE FROM items WHERE chrt_id IS NOT NULL;
DELETE FROM payment WHERE transaction IS NOT NULL;
DELETE FROM wb_order WHERE order_uid IS NOT NULL;